apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: aws-secrets
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: production/aws-credentials
        property: access-key-id
    - secretKey: secret-access-key
      remoteRef:
        key: production/aws-credentials
        property: secret-access-key
