apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: 
      "arn:aws:secretsmanager:us-east-1:222634373:secret:nestjs-db-credentials-7s0qpp"
        jmesPath:
          - path: DB_USER
            objectAlias: db-user
          - path: DB_PASSWORD
            objectAlias: db-password

# not "arn:aws:secretsmanager:us-east-1:222634373:secret:nestjs-db-credentials-7s0qpp"