replicaCount: 2

image:
  repository: your-dockerhub-username/nestjs-eks
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  hosts:
    - host: nestjs.yourdomain.com
      paths:
        - path: /
          pathType: ImplementationSpecific

awsSecrets:
  name: "your-aws-secret-name"
  region: "us-east-1"
